@startuml
title DTO Class Diagram

class TermRequestDTO {
    - String name
    - String startDate
    - String endDate
}

class TermResponseDTO {
    - Long termId
    - String name
    - String startDate
    - String endDate
    - List<CourseDTO> courses
}

class CourseBaseDTO {
    - String courseCode
    - String name
    - Long credit
}

class CourseDTO {
    - Long courseId
    - List<TopicDTO> topics
    - List<AssignmentDTO> assignments
    - List<ExamDTO> exams
}

class TopicDTO {
    - String name
    - Long difficulty
    - Long confidence
    - Long estimatedStudyTime
    - ExamType examType
}

class AssignmentDTO {
    - String id
    - String name
    - LocalDate dueDate
    - LocalTime dueTime
    - Long estimatedTime
    - List<String> associatedTopicIds
    - ExamType examType
    - Boolean isCompleted
}

class ExamDTO {
    - String id
    - ExamType type
    - LocalDate date
    - LocalTime startTime
    - LocalTime endTime
}

class StudyPreferenceDTO {
    - String userUid
    - Integer minSessionDuration
    - Integer maxSessionDuration
    - List<String> preferredStudyTimes
    - String revisionFrequency
    - Integer breakDurations
}

class AvailabilityDTO {
    - LocalDate date
    - LocalTime startTime
    - LocalTime endTime
}

class GeneratePlanRequestDTO {
    - StudyPreferenceDTO studyPreference
    - StudySetupDTO studySetup
}

class StudySetupDTO {
    - TermResponseDTO term
    - List<AvailabilityDTO> availabilities
}

class SessionDTO {
    - String sessionId
    - Long courseId
    - Long duration
    - SessionType type
    - LocalDate date
    - LocalTime start
    - LocalTime end
    - Boolean isScheduled
    - String topicId
    - String assignmentId
}

class ScheduleDTO {
    - List<SessionDTO> study_plan
    - List<SessionDTO> unscheduled_plan
}

class SessionViewDTO {
    - String sessionId
    - String courseCode
    - String topicName
    - String assignmentName
    - LocalDate date
    - LocalTime start
    - LocalTime end
    - Long duration
    - SessionType type
    - Boolean isScheduled
    - Boolean isCompleted
}

class ScheduleViewDTO {
    - List<SessionViewDTO> studyPlan;
    - List<SessionViewDTO> unscheduledPlan;
}

CourseResponseDTO --|> CourseBaseDTO
CourseResponseDTO --> CourseId
TermResponseDTO --> CourseResponseDTO
TermDTO --> CourseDTO
StudySetupDTO --> TermDTO
AIPlanRequestDTO --> StudyPreferenceDTO
AIPlanRequestDTO --> AvailabilityDTO
AIPlanRequestDTO --> CourseDTO
AIPlanRequestDTO --> TopicDTO
AIPlanRequestDTO --> AssignmentDTO
AIPlanRequestDTO --> ExamDTO

@enduml