@startuml
title Entity Class Diagram

enum ExamType {
    MIDTERM
    FINAL
}

class User {
    - String uid
    - String email
}

class Term {
    - Long termId
    - String name
    - LocalDate startDate
    - LocalDate endDate
}

class Course {
    - Long courseId
    - String courseCode
    - String name
    - Long credit
}

class Topic {
    - String id
    - String name
    - Long difficulty
    - Long confidence
    - Long estimatedStudyTime
    - ExamType examType
}

class Assignment {
    - Long id
    - String name
    - LocalDate dueDate
    - LocalTime dueTime
    - Long estimatedTime
    - Boolean isCompleted
}

class Exam {
    - String id
    - ExamType type
    - LocalDate date
    - LocalTime startTime
    - LocalTime endTime
}

class Availability {
    - Long id
    - LocalDate date
    - LocalTime startTime
    - LocalTime endTime
}

class StudyPreference {
    - String userUid
    - Integer minSessionDuration
    - Integer maxSessionDuration
    - List<String> preferredStudyTimes
    - String revisionFrequency
    - Integer breakDurations
}

class Session {
    - Sring sessionId
    - LocalDate date
    - LocalTime start
    - LocalTime end
    - Long duration
    - Boolean isCompleted
    - SessionType type
}

class Schedule {
    - Long id
    - String generatedAt
    - ExamType examType
}

@enduml
