@startuml
title Enum Class Diagram

enum ExamType {
    MIDTERM
    FINAL
}

enum SessionType {
    OVERVIEW
    CORE_STUDY
    FINAL_REVIEW
    ASSIGNMENT
}

enum FocusStatus {
    INCOMPLETE   
    FOCUSING
    PAUSED
    COMPLETED    
}

enum Range {
    DAY
    WEEK
    MONTH
    YEAR
}

@enduml
