@startuml
title UML Class Diagram - Controller Layer

class StudyGroupController {
    - studyGroupService : StudyGroupService
    + createGroup(dto: GroupRequestDTO) : ResponseEntity<?>
    + joinGroup(dto: JoinGroupRequestDTO) : ResponseEntity<?>
}

class SessionController {
    - sessionService : SessionService
    + getToDoList() : ResponseEntity<?>
    + startFocusSession(request: StartFocusSessionDTO): ResponseEntity<?>
}


class StudyAnalyticsController {
    - studyAnalyticsService : StudyAnalyticsService
    + getAnalytics(range: Range) : ResponseEntity<StudyAnalyticsDTO>
}

@enduml
