@startuml
class User {
    - Long id
    - String uid
    - String email
    ...
}

class FocusSession {
    - Long id
    - LocalDateTime startedAt
    - LocalDateTime endedAt
    - Boolean isShared
}

class StudySession {
    - Long id
    - String title
    - LocalDateTime scheduledAt
    - Boolean completed
    - String subject
    - Integer actualDurationInMinutes
}

class StudyGroup {
    - Long id
    - String name
    - String imageUrl
    - String joinCode
}

class GroupMember {
    - Long id
}
@enduml
